@echo off

REM hosts discovered by https://twitter.com/EveningStarNM

echo # MICROSOFT DATA HARVESTING >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 compatexchange.cloudapp.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 a-0001.a-msedge.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 choice.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 choice.microsoft.com.nsatc.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 corpext.msitadfs.glbdns2.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 df.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 oca.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 redir.metaservices.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 services.wes.df.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 settings-sandbox.data.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sls.update.microsoft.com.akadns.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.df.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 statsfe2.ws.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telecommand.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.appex.bing.net >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.urs.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex-sandbox.data.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex-win.data.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex.data.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.ppe.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.telemetry.microsoft.com >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net >> "%windir%\system32\drivers\etc\hosts"
echo # END MICROSOFT DATA HARVESTING >> "%windir%\system32\drivers\etc\hosts"

pause
