@echo off

REM Hosts list by https://twitter.com/EveningStarNM

echo # MICROSOFT DATA HARVESTING                                 >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 www.msftncsi.com                                  >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 pre.footprintpredict.com                          >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 cs1.wpc.v0cdn.net                                 >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 a-0001.a-msedge.net                               >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 az361816.vo.msecnd.net                            >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 az512334.vo.msecnd.net                            >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 choice.microsoft.com                              >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 choice.microsoft.com.nsatc.net                    >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 compatexchange.cloudapp.net                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 corp.sts.microsoft.com                            >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 corpext.msitadfs.glbdns2.microsoft.com            >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 df.telemetry.microsoft.com                        >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 diagnostics.support.microsoft.com                 >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 fe2.update.microsoft.com.akadns.net               >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 feedback.microsoft-hohm.com                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 feedback.search.microsoft.com                     >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 feedback.windows.com                              >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 i1.services.social.microsoft.com                  >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 i1.services.social.microsoft.com.nsatc.net        >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 oca.telemetry.microsoft.com                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 oca.telemetry.microsoft.com.nsatc.net             >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 preview.msn.com                                   >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 rad.msn.com                                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 redir.metaservices.microsoft.com                  >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 reports.wes.df.telemetry.microsoft.com            >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 services.wes.df.telemetry.microsoft.com           >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 settings-sandbox.data.microsoft.com               >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sls.update.microsoft.com.akadns.net               >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.df.telemetry.microsoft.com                    >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.telemetry.microsoft.com                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 sqm.telemetry.microsoft.com.nsatc.net             >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 statsfe1.ws.microsoft.com                         >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 statsfe2.update.microsoft.com.akadns.net          >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 statsfe2.ws.microsoft.com                         >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 survey.watson.microsoft.com                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telecommand.telemetry.microsoft.com               >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telecommand.telemetry.microsoft.com.nsatc.net     >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.appex.bing.net                          >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.microsoft.com                           >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 telemetry.urs.microsoft.com                       >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex-sandbox.data.microsoft.com                 >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex-win.data.microsoft.com                     >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 vortex.data.microsoft.com                         >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.live.com                                   >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.microsoft.com                              >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.ppe.telemetry.microsoft.com                >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.telemetry.microsoft.com                    >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 watson.telemetry.microsoft.com.nsatc.net          >> "%windir%\system32\drivers\etc\hosts"
echo 127.0.0.1 wes.df.telemetry.microsoft.com                    >> "%windir%\system32\drivers\etc\hosts"
echo # END MICROSOFT DATA HARVESTING                             >> "%windir%\system32\drivers\etc\hosts"

pause
